// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvqOGTqsNTSc0u64DWmAVNTCLB858wucM',
    appId: '1:12406294920:web:d23a736d2f6c7f407f123d',
    messagingSenderId: '12406294920',
    projectId: 'worldofwood-fc27b',
    authDomain: 'worldofwood-fc27b.firebaseapp.com',
    storageBucket: 'worldofwood-fc27b.firebasestorage.app',
    measurementId: 'G-GF63G9RLHG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbJN8vV9aiYylzoSRTMjBdPO8-ECj5Ucs',
    appId: '1:12406294920:android:a0c78974ae199da97f123d',
    messagingSenderId: '12406294920',
    projectId: 'worldofwood-fc27b',
    storageBucket: 'worldofwood-fc27b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBaZACxoZNLnHxsOwlKoaxbsjcQMeRjzM',
    appId: '1:12406294920:ios:b5cd98beecc9ad6f7f123d',
    messagingSenderId: '12406294920',
    projectId: 'worldofwood-fc27b',
    storageBucket: 'worldofwood-fc27b.firebasestorage.app',
    iosBundleId: 'com.example.worldOfWood',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBaZACxoZNLnHxsOwlKoaxbsjcQMeRjzM',
    appId: '1:12406294920:ios:b5cd98beecc9ad6f7f123d',
    messagingSenderId: '12406294920',
    projectId: 'worldofwood-fc27b',
    storageBucket: 'worldofwood-fc27b.firebasestorage.app',
    iosBundleId: 'com.example.worldOfWood',
  );
}
